name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stream-dl:$(date +%s) && docker-slim build --target stream-dl:$(date +%s) --tag stream-dl:slim$(date +%s) --http-probe=false
